# Generated by Django 5.2.6 on 2025-09-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutdoorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Outdoor locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutdoorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the place of activity.', max_length=150)),
                ('activity', models.CharField(choices=[('hike', 'Hike Trail'), ('camping', 'Camping'), ('picnic', 'Picnic Area'), ('other', 'Other')], default='other', max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='outdoor.outdoorlocation')),
            ],
            options={
                'verbose_name_plural': 'Outdoor activities',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'activity'), name='unique_activity_per_name')],
            },
        ),
    ]
