# Generated by Django 5.2.6 on 2025-09-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outdooractivity',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='outdooractivity',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='outdoorlocation',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='outdoorlocation',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.AlterUniqueTogether(
            name='outdooractivity',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='outdooractivity',
            name='activity',
            field=models.CharField(choices=[('hike', 'Hike Trail'), ('park', 'Park'), ('sport', 'Sports Ground'), ('bird_watching', 'Bird Watching'), ('camping', 'Camping'), ('fishing', 'Fishing'), ('market', 'Outdoor Market'), ('picnic', 'Picnic Area'), ('photography', 'Photography'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='outdooractivity',
            constraint=models.UniqueConstraint(fields=('name', 'activity'), name='unique_activity_per_name'),
        ),
    ]
