# Generated by Django 5.2.6 on 2025-09-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoor', '0002_rename_latitude_outdooractivity_lat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outdooractivity',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='outdoorlocation',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='outdoorlocation',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
