# Generated by Django 5.2.6 on 2025-09-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Singing', 'Singing'), ('Charades', 'Charades')], help_text='Type of indoor game (Singing or Charades).', max_length=100)),
                ('active_status', models.BooleanField(default=True, help_text='Indicates whether this game is currently active.')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the team.', max_length=100)),
                ('members', models.TextField(help_text='Comma-separated list of team members (e.g., Alice,Bob,Charlie).')),
                ('score', models.IntegerField(default=0, help_text='Current score of the team.')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(help_text='Sequential number of the round (e.g., 1, 2, 3).')),
                ('hint', models.CharField(help_text='Hint for the round (e.g., word for charades).', max_length=255)),
                ('points', models.IntegerField(default=0, help_text='Points awarded to the winning team in this round.')),
                ('game', models.ForeignKey(help_text='The game this round belongs to.', on_delete=django.db.models.deletion.CASCADE, to='indoor.game')),
                ('winner', models.ForeignKey(blank=True, help_text='The team that won this round (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indoor.team')),
            ],
        ),
    ]
