# Generated by Django 5.2.6 on 2025-09-10 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='content_type',
            field=models.CharField(choices=[('charades', 'Charades'), ('singing', 'Singing')], default='', help_text='Type of content for this round.', max_length=50),
        ),
        migrations.AddField(
            model_name='round',
            name='team',
            field=models.ForeignKey(default=None, help_text='The team participating in this round.', on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='indoor.team'),
        ),
        migrations.AlterField(
            model_name='round',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, help_text='The team that won this round (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rounds', to='indoor.team'),
        ),
    ]
